---
- hosts: vagrant
  sudo: yes
  tasks:
    - name: ensure default packages
      yum: name={{item}}
      with_items:
        - screen
        - rsync        
        - python-setuptools
    - name: install required python tools
      easy_install: name={{item}}
      with_items:
        - pip
        - supervisor
    - name: copy screen.rc
      copy: src=files/home/vagrant/.screenrc dest=/home/vagrant/.screenrc owner=vagrant mode=0644
      sudo: no
    - name: stop iptables
      service: name=iptables state=stopped enabled=no
    - name: install nginx yum repo
      yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
      tags: nginx_install
    - name: install nginx
      yum: name=nginx enablerepo=nginx state=installed
      tags: nginx_install
      notify:
      - restart nginx
    - name: enable nginx
      service: name=nginx enabled=yes
      tags: nginx_install
    - name: copy nginx conf
      copy: src=files/etc/nginx/conf.d/default.conf dest=/etc/nginx/conf.d/default.conf backup=yes mode=644
      notify: restart nginx
    - name: create app directory
      file: dest=app state=directory
      sudo: no
    - name: create supervisord related directory
      file: dest=/etc/supervisord.d state=directory
    - name: copy supervisord related files
      copy: src=files/{{item.path}} dest=/{{item.path}} mode={{item.mode}}
      with_items:
        - { path: etc/init.d/supervisord, mode: "0755" }
        - { path: etc/sysconfig/supervisord, mode: "0644" }
        - { path: etc/supervisord.conf, mode: "0644" }
      notify: restart supervisord
    - name: copy app setting for supervisord
      template: src=templates/etc/supervisord.d/todo.ini.j2 dest=/etc/supervisord.d/todo.ini mode=0644
      notify: restart supervisord
    - name: enable supervisord
      service: name=supervisord enabled=yes
      notify: restart supervisord
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart supervisord
      service: name=supervisord state=restarted